spring:
  datasource:
    url: jdbc:postgresql://db:5432/challenge_db
    username: liam
    password: craftworks
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
